package net.af0.where.e2ee

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertTrue

/**
 * Known-input/output test vectors for every crypto primitive.
 *
 * These run on ALL platforms (JVM, Android, iOS) via the commonTest source set.
 * On iOS the actual implementations are the Security framework / CommonCrypto
 * cinterop; on JVM/Android they use BouncyCastle / JCA.
 *
 * Catching a failure here on one platform means that platform's implementation
 * diverges from the spec — most likely an Ed25519 seed-format mismatch.
 */
class CryptoPrimitivesVectorTest {
    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private fun hex(s: String): ByteArray {
        val clean = s.replace(" ", "").replace("\n", "")
        check(clean.length % 2 == 0) { "odd hex length" }
        return ByteArray(clean.length / 2) { i ->
            clean.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
    }

    // -----------------------------------------------------------------------
    // SHA-256 (FIPS 180-4 example)
    // -----------------------------------------------------------------------

    @Test
    fun `sha256 of 'abc'`() {
        val input = "abc".encodeToByteArray()
        // Standard SHA256("abc") = ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad
        val expected =
            hex(
                "ba7816bf8f01cfea414140de5dae2223" +
                    "b00361a396177a9cb410ff61f20015ad",
            )
        assertContentEquals(expected, sha256(input))
    }

    @Test
    fun `sha256 of empty string`() {
        val expected =
            hex(
                "e3b0c44298fc1c149afbf4c8996fb924" +
                    "27ae41e4649b934ca495991b7852b855",
            )
        assertContentEquals(expected, sha256(ByteArray(0)))
    }

    // -----------------------------------------------------------------------
    // HMAC-SHA-256 (RFC 4231 Test Case 1)
    // -----------------------------------------------------------------------

    @Test
    fun `hmacSha256 RFC 4231 test case 1`() {
        val key = hex("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b")
        val data = "Hi There".encodeToByteArray()
        val expected =
            hex(
                "b0344c61d8db38535ca8afceaf0bf12b" +
                    "881dc200c9833da726e9376c2e32cff7",
            )
        assertContentEquals(expected, hmacSha256(key, data))
    }

    // -----------------------------------------------------------------------
    // X25519 (RFC 7748 §6.1 test vector)
    // -----------------------------------------------------------------------

    @Test
    fun `x25519 DH is symmetric and produces known shared secret`() {
        // Vectors generated by BouncyCastle 1.80 (bcprov-jdk18on).
        // If this test fails on iOS, the Apple Security framework derives
        // a different X25519 shared secret — a cross-platform incompatibility.
        val alicePriv =
            hex(
                "50420e9a9fcb83c472bd72409051fbde" +
                    "3ad8211512791460a9526d634c9cc266",
            )
        val alicePub =
            hex(
                "d16c7e378eb59316a29e0e223f9a7207" +
                    "f689dcb7e03ccc6274b5ccca7782e176",
            )
        val bobPriv =
            hex(
                "a80ef2e230c64b86241cdee3f24c65a2" +
                    "f6d6423e32f3704421e7bf9605e1a156",
            )
        val bobPub =
            hex(
                "9d7ec2254285d78fc18c023cad4e9302" +
                    "2106db7e7f4e284a4ff785b288504528",
            )
        val shared =
            hex(
                "3f52110c9b19ad36b17349401dad1286" +
                    "e8854713f1f6ae9c6bba9b1c768a9f3c",
            )

        val aliceShared = x25519(alicePriv, bobPub)
        val bobShared = x25519(bobPriv, alicePub)

        assertContentEquals(
            shared,
            aliceShared,
            "Alice's shared secret must match known vector",
        )
        assertContentEquals(
            shared,
            bobShared,
            "Bob's shared secret must match known vector (DH must be symmetric)",
        )
    }

    // -----------------------------------------------------------------------
    // Ed25519 (RFC 8032 §5.1 Test Vector 1)
    //
    // CRITICAL: this vector catches private-key seed-format mismatches between
    // Apple Security framework and BouncyCastle.  Both must treat the 32-byte
    // private key as the seed (random nonce), not the expanded scalar.
    // -----------------------------------------------------------------------

    @Test
    fun `ed25519 seed derives consistent public key across platforms`() {
        // Vectors generated by BouncyCastle 1.80 (bcprov-jdk18on).
        // CRITICAL: if this fails on iOS the Apple Security framework interprets
        // the 32-byte private key differently (e.g. as the expanded scalar
        // rather than the seed) — a cross-platform protocol-breaking mismatch.
        val seed =
            hex(
                "bdded92f52dd3e8fbbbad28833c986a6" +
                    "dda3ec7a22076e017f5c7666c47715b7",
            )
        val expectedPub =
            hex(
                "7352a5566108b004a73004228ae05f4c" +
                    "ce74f750c77d10a2046a76372a62045f",
            )

        val sig = ed25519Sign(seed, ByteArray(0))
        assertTrue(
            ed25519Verify(expectedPub, ByteArray(0), sig),
            "Signature produced with known seed must verify against its derived public key",
        )
    }

    @Test
    fun `ed25519 verify RFC 8032 vector 1 signature`() {
        val pub =
            hex(
                "d75a980182b10ab7d54bfed3c964073a" +
                    "0ee172f3daa62325af021a68f707511a",
            )
        // RFC 8032 §5.1 Test Vector 1: empty message
        val sig =
            hex(
                "e5564300c360ac729086e2cc806e828a" +
                    "84877f1eb8e5d974d873e06522490155" +
                    "5fb8821590a33bacc61e39701cf9b46b" +
                    "d25bf5f0595bbe24655141438e7a100b",
            )
        assertTrue(
            ed25519Verify(pub, ByteArray(0), sig),
            "RFC 8032 test vector 1 signature must verify",
        )
    }

    @Test
    fun `ed25519 rejects invalid signature`() {
        val pub =
            hex(
                "d75a980182b10ab7d54bfed3c964073a" +
                    "0ee172f3daa62325af021a68f707511a",
            )
        val badSig = ByteArray(64) // all-zero signature is always invalid
        assertTrue(
            !ed25519Verify(pub, ByteArray(0), badSig),
            "All-zero signature must not verify",
        )
    }

    @Test
    fun `ed25519 round-trip sign and verify`() {
        val kp = generateEd25519KeyPair()
        val msg = "hello world".encodeToByteArray()
        val sig = ed25519Sign(kp.priv, msg)
        assertTrue(ed25519Verify(kp.pub, msg, sig))
        assertTrue(
            !ed25519Verify(kp.pub, msg + byteArrayOf(0), sig),
            "Signature must not verify for different message",
        )
    }

    // -----------------------------------------------------------------------
    // AES-256-GCM (NIST GCM test vector: K=0^32, IV=0^12, P=empty, A=empty)
    // -----------------------------------------------------------------------

    @Test
    fun `aesgcm NIST empty-plaintext vector`() {
        val key = ByteArray(32) // all zeros
        val nonce = ByteArray(12) // all zeros
        val aad = ByteArray(0)
        // NIST test vector: ciphertext = empty, tag = 530f8afbc74536b9a963b4f1c4cb738b
        val expectedCtTag = hex("530f8afbc74536b9a963b4f1c4cb738b")
        assertContentEquals(expectedCtTag, aesgcmEncrypt(key, nonce, ByteArray(0), aad))
    }

    @Test
    fun `aesgcm round-trip with plaintext and aad`() {
        val key = ByteArray(32) { it.toByte() }
        val nonce = ByteArray(12) { (it + 1).toByte() }
        val aad = "sender:alice".encodeToByteArray()
        val plaintext = "37.7749,-122.4194".encodeToByteArray()

        val ctTag = aesgcmEncrypt(key, nonce, plaintext, aad)
        val decrypted = aesgcmDecrypt(key, nonce, ctTag, aad)

        assertContentEquals(plaintext, decrypted)
    }

    @Test
    fun `aesgcm decryption fails on tag corruption`() {
        val key = ByteArray(32) { it.toByte() }
        val nonce = ByteArray(12)
        val pt = "test".encodeToByteArray()
        val ctTag = aesgcmEncrypt(key, nonce, pt, ByteArray(0)).copyOf()
        // Flip a bit in the tag (last 16 bytes)
        ctTag[ctTag.size - 1] = (ctTag[ctTag.size - 1].toInt() xor 1).toByte()

        val threw =
            try {
                aesgcmDecrypt(key, nonce, ctTag, ByteArray(0))
                false
            } catch (_: Exception) {
                true
            }
        assertTrue(threw, "Corrupted tag must cause decryption to fail")
    }
}
