default_platform(:android)

platform :android do
  desc "Build debug and release AAB"
  lane :build do
    gradle(task: "bundle", build_type: "Release")
    gradle(task: "bundle", build_type: "Debug")
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store
  end
end
